s = set()

num = int(input("enter the no. 1:"))
s.add(num)
num = int(input("enter the no. 2:"))
s.add(num)
num = int(input("enter the no. 3:"))
s.add(num)
num = int(input("enter the no. 4:"))
s.add(num)
num = int(input("enter the no. 5:"))
s.add(num)
num = int(input("enter the no. 6:"))
s.add(num)
num = int(input("enter the no. 7:"))
s.add(num)
num = int(input("enter the no. 8:"))
s.add(num)
print(s)